version: '3'
services:
  web:
    build: .
    container_name: ez_rce_pro
    ports:
      - "9999:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/sites-available/default
